### ISSUE TITLE
site profiles are not consistent after profile deletion

### ISSUE THREAD

**Issue by greizgh** [gustavomondron/twik-for-chrome#3]
Step to reproduce:
- create three profiles, let's say profile 1, profile 2 and profile 3
- select profile 2 for a website (so that it's registered as site profile)
- delete profile 2
- go on website, profile 3 will be selected

In data.js, getProfileForSite use index in profile list to return the right profile but index will change on profile removal.

**Comment by gustavomondron** [comment]
You're right, removing profiles leads to inconsistencies. Thanks for pointing it out.

**Comment by gustavomondron** [comment]
Fixed in 0.4.3
